spring:
  datasource:
    url: jdbc:postgresql://db.pplgqbqwazjgufqwtixs.supabase.co:5432/postgres
    username: postgres
    password: "uniamerica2026"
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration