ALTER TABLE cargo RENAME TO tb_cargo;
ALTER TABLE tb_cargo RENAME COLUMN cargoid TO id;
ALTER TABLE tb_cargo RENAME COLUMN cargonome TO name;
ALTER TABLE tb_cargo ADD CONSTRAINT uk_tb_cargo_name UNIQUE (name);

ALTER TABLE usuario RENAME TO tb_user;
ALTER TABLE tb_user RENAME COLUMN usuarioid TO id;
ALTER TABLE tb_user RENAME COLUMN usuarionome TO name;
ALTER TABLE tb_user RENAME COLUMN usuarioemail TO email;
ALTER TABLE tb_user RENAME COLUMN usuariosenharest TO password_hash;
ALTER TABLE tb_user RENAME COLUMN usuarioavatarurl TO avatar_url;
ALTER TABLE tb_user RENAME COLUMN usuariocargoid TO cargo_id;
ALTER TABLE tb_user RENAME COLUMN usuarioativo TO status;
ALTER TABLE tb_user RENAME COLUMN usuarioxp TO xp;
ALTER TABLE tb_user RENAME COLUMN usuarioelo TO elo;
ALTER TABLE tb_user RENAME COLUMN usuariocriadoem TO created_at;
ALTER TABLE tb_user RENAME COLUMN usuarioatualizadoem TO updated_at;
ALTER TABLE tb_user RENAME COLUMN usuariocriadopor TO created_by;
ALTER TABLE tb_user RENAME COLUMN usuarioatualizadopor TO updated_by;
UPDATE tb_user SET updated_at = created_at WHERE updated_at IS NULL;
ALTER TABLE tb_user ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_user ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE projeto RENAME TO tb_project;
ALTER TABLE tb_project RENAME COLUMN projetoid TO id;
ALTER TABLE tb_project RENAME COLUMN projetonome TO name;
ALTER TABLE tb_project RENAME COLUMN projetodescricao TO description;
ALTER TABLE tb_project RENAME COLUMN projetostatus TO status;
ALTER TABLE tb_project RENAME COLUMN projetoprioridade TO priority;
ALTER TABLE tb_project RENAME COLUMN projetodatainicio TO start_date;
ALTER TABLE tb_project RENAME COLUMN projetoprazo TO dead_line;
ALTER TABLE tb_project RENAME COLUMN projetoproprietarioid TO owner_id;
ALTER TABLE tb_project RENAME COLUMN projetocriadoem TO created_at;
ALTER TABLE tb_project RENAME COLUMN projetoatualizadoem TO updated_at;
ALTER TABLE tb_project ADD COLUMN created_by BIGINT;
ALTER TABLE tb_project ADD COLUMN updated_by BIGINT;
UPDATE tb_project SET description = '' WHERE description IS NULL;
UPDATE tb_project SET start_date = CURRENT_TIMESTAMP WHERE start_date IS NULL;
UPDATE tb_project SET dead_line = CURRENT_TIMESTAMP WHERE dead_line IS NULL;
UPDATE tb_project SET updated_at = created_at WHERE updated_at IS NULL;
ALTER TABLE tb_project ALTER COLUMN description SET NOT NULL;
ALTER TABLE tb_project ALTER COLUMN start_date TYPE DATE USING start_date::date;
ALTER TABLE tb_project ALTER COLUMN start_date SET NOT NULL;
ALTER TABLE tb_project ALTER COLUMN dead_line TYPE DATE USING dead_line::date;
ALTER TABLE tb_project ALTER COLUMN dead_line SET NOT NULL;
ALTER TABLE tb_project ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_project ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE tarefa RENAME TO tb_task;
ALTER TABLE tb_task RENAME COLUMN tarefaid TO id;
ALTER TABLE tb_task RENAME COLUMN tarefatitulo TO title;
ALTER TABLE tb_task RENAME COLUMN tarefadescricao TO description;
ALTER TABLE tb_task RENAME COLUMN tarefastatus TO status;
ALTER TABLE tb_task RENAME COLUMN tarefaprioridade TO priority;
ALTER TABLE tb_task RENAME COLUMN tarefaresponsavelid TO assignee_id;
ALTER TABLE tb_task RENAME COLUMN tarefacriadorid TO creator_id;
ALTER TABLE tb_task RENAME COLUMN tarefaprazo TO dead_line;
ALTER TABLE tb_task RENAME COLUMN tarefacriadoem TO created_at;
ALTER TABLE tb_task RENAME COLUMN tarefacriadopor TO created_by;
ALTER TABLE tb_task RENAME COLUMN tarefaatualizadopor TO updated_by;
ALTER TABLE tb_task RENAME COLUMN tarefaprojetoid TO project_id;
ALTER TABLE tb_task RENAME COLUMN tarefaatualizadoem TO updated_at;
ALTER TABLE tb_task RENAME COLUMN tarefaconcluidoem TO completed_at;
UPDATE tb_task SET description = '' WHERE description IS NULL;
UPDATE tb_task SET dead_line = CURRENT_TIMESTAMP WHERE dead_line IS NULL;
UPDATE tb_task SET updated_at = created_at WHERE updated_at IS NULL;
ALTER TABLE tb_task ALTER COLUMN description SET NOT NULL;
ALTER TABLE tb_task ALTER COLUMN dead_line TYPE DATE USING dead_line::date;
ALTER TABLE tb_task ALTER COLUMN dead_line SET NOT NULL;
ALTER TABLE tb_task ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_task ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE transacaoxp RENAME TO tb_xp_transaction;
ALTER TABLE tb_xp_transaction RENAME COLUMN transacaoxpid TO id;
ALTER TABLE tb_xp_transaction RENAME COLUMN transacaoxpusuarioid TO user_id;
ALTER TABLE tb_xp_transaction RENAME COLUMN transacaoxpquantidade TO amount;
ALTER TABLE tb_xp_transaction RENAME COLUMN transacaoxpreferenciaid TO reference_id;
ALTER TABLE tb_xp_transaction RENAME COLUMN transacaoxpcriadoem TO created_at;
ALTER TABLE tb_xp_transaction ADD COLUMN reason VARCHAR(250);
ALTER TABLE tb_xp_transaction ADD COLUMN reference_type VARCHAR(100);
ALTER TABLE tb_xp_transaction ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tb_xp_transaction ADD COLUMN created_by BIGINT;
ALTER TABLE tb_xp_transaction ADD COLUMN updated_by BIGINT;
UPDATE tb_xp_transaction SET reason = 'Ajuste de XP' WHERE reason IS NULL;
ALTER TABLE tb_xp_transaction ALTER COLUMN reason SET NOT NULL;
ALTER TABLE tb_xp_transaction ALTER COLUMN updated_at SET NOT NULL;
